name: Deploy

on:
  push:
    branches: [main]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Publish
        run: dotnet publish ./src/Server/TheArchives.Server.csproj -o ./publish -c Release -v n

      - name: Deploy
        run: rsync -avuz ./publish/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/the-archives/publish-swap/
  
      - name: Swap
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "'mv' /var/www/the-archives/publish /var/www/the-archives/publish-old && 'mv' /var/www/the-archives/publish-swap /var/www/the-archives/publish"
  
      - name: Restart Kestrel
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sudo systemctl restart ${{ secrets.KESTREL_APP_NAME }}"

      - name: Remove Swap Dir
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "'rm' -rf /var/www/the-archives/publish-old"
