name: Test

on:
  pull_request:
    branches: [master]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.100-preview.3.21202.5

      - name: Test
        run: dotnet test -v n